config/routes.rb
Rails.application.routes.draw do
  get '/', to:'sessions#new', as: 'new_session'
  resources :sessions, only: [:index,:new, :create]
  get '/sessions/logout', in: 'sessions#logout', as: 'logout_session'
  resources :home_pages, only: [:index]
  resources :bookings
  resources :guests
  resources :hotels, only: [:index, :show]
  resources :rooms, only: [:index, :show]
  resources :reviews
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :guest
  belongs_to :room

  validates :number_of_guest, :presence => true
  validates_inclusion_of :number_of_guest, :in => 1..6, :message => 'must be between 1 and 6'

  validates :check_in_date, :check_out_date, presence: true
  validate :check_out_date_after_check_in_date

  private

  def check_out_date_after_check_in_date  
    if check_out_date < check_in_date
      errors.add(:check_in_date, "must be before Check-out date")
    end
  end 

  end
  

app/models/guest.rb
class Guest < ApplicationRecord
    has_secure_password
    has_many :bookings
    has_many :reviews
    has_many :rooms, through: :bookings

end

app/models/hotel.rb
class Hotel < ApplicationRecord
    has_many :rooms
    has_many :reviews
    has_many :bookings, through: :rooms
end

app/models/parser/data_parse.rb
require 'csv'
table = CSV.parse(File.read("app/models/parser/hotel_data.csv"), headers: true, :encoding => 'ISO-8859-1')
table.each do |row|
    rowH = row.to_hash
    if rowH["image"] && rowH["name"] && rowH["city"] && rowH["country"]
        puts rowH["country"]
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :hotel
  belongs_to :guest

  validates :title, presence: true
  validates :content, presence: true

  validates :title, length: {minimum: 3, maximum: 35}
  validates :content, length: {minimum: 5, maximum: 250}


end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :hotel 
    has_many :bookings
    has_many :guests, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def user 
        if session[:user]
            user = Guest.find(session[:user])
        end
    end

    def valid?
        redirect_to new_session_path unless user
    end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :valid?
  def index
  end

  def new
    @booking = Booking.new 
    @room_id = params[:room_id]
    @guest_id = session[:user]
  end

  def create
    room= Room.find(params[:booking][:room_id])
    @room_id = params[:booking][:room_id]
    @guest_id = session[:user]
    # byebug
    if params[:booking]["check_in_date"].to_i > 0  && params[:booking]["check_out_date"].to_i > 0
      number_of_day = check_date_diff(params[:booking]["check_in_date"],params[:booking]["check_out_date"])
      params[:booking][:cost] = number_of_day * room.rate
    end
    
    @booking = Booking.new(booking_params)
    # byebug  
    if @booking.save
      # byebug
      redirect_to booking_path(@booking)
    else 
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @guest_id = session[:user]
  end

  def edit
    @booking = Booking.find(params[:id])
    @guest_id = session[:user]
    @room_id = @booking.room.id
  end

  def update
    @booking = Booking.find(params[:id])
    room= Room.find(params[:booking][:room_id])
   
    @guest_id = session[:user]
    @room_id = @booking.room.id
    if params[:booking]["check_in_date"].to_i > 0  && params[:booking]["check_out_date"].to_i > 0
      number_of_day = check_date_diff(params[:booking]["check_in_date"],params[:booking]["check_out_date"])
      params[:booking][:cost] = number_of_day * room.rate
    end
 
    
    if @booking.update(booking_params) 
      # byebug
      redirect_to booking_path(@booking)
    else 
      render :new
    end

  end

  def destroy
    booking = Booking.find(params[:id])
    guest_id = booking.guest.id 
    booking.delete 
    redirect_to guest_path(guest_id)
  end

  def check_date_diff(start_date_string,end_date_string)
    start_date = Date.parse(start_date_string)
    end_date = Date.parse(end_date_string)
    diff = (end_date - start_date).to_i
  end

  private 
  def booking_params
    params.require(:booking).permit(:check_in_date, :check_out_date,:number_of_guest,:booking_date,:cost,:guest_id, :room_id)
  end

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :valid?, except: [:new,:create]
  def index
    @guests = Guest.all
  end

  def new
    @guest = Guest.new
  end

  def create
    guest = Guest.create(guest_params)
    session[:user] = guest.id 
    redirect_to home_pages_path
  end

  def show
    @guest = Guest.find(params[:id])
    @bookings = @guest.bookings
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private 
  def guest_params
    params.require(:guest).permit(:first_name, :last_name, :email,:password)
  end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  before_action :valid?
  def index
    @rooms = Room.all
    # @uniq_cities = hotels.select(:city).uniq.sort
    # byebug
    @cities = Hotel.all.map{|h| h.city}
    @uniq_cities = @cities.uniq.sort
    if params[:city]
      # byebug
      @hotels = Hotel.select{|h| h.city == params[:city]}
      # byebug
    else
      @hotels = Hotel.all
      # byebug
    end
  end 

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :valid?
  def index
    @hotels = Hotel.all
  end

  def show
    @hotel = Hotel.find(params[:id])
    @i=0
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :valid?

    def index
        @guest = Guest.find(session[:user])
        @hotels = Hotel.all
    end

    def new
        @review = Review.new
        @hotel = Hotel.find(params[:hotel_id])
        @guest = Guest.find(session[:user])

    end

    def create 
        params[:review][:guest_id] = session[:user]
        # byebug
        @hotel = Hotel.find(params[:review][:hotel_id])
        @review = Review.new(review_params)
        if @review.save
            redirect_to reviews_path
        else
            render :new
        end

    end

    private

    def review_params
        params.require(:review).permit(:title, :star, :content, :hotel_id, :guest_id)
    end




end #end of Controller class

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :valid?
  def index
    @rooms = Room.all
  end

  def show
    @booking = Booking.new 
    @room = Room.find(params[:id])
    @guest = Guest.find_by(id: session[:user])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :valid?, except: [:index,:new, :create]
  
  def index
    
  end

  def new
  end

  def create
    user = Guest.find_by(email: params[:email])
    if (user && user.authenticate(params[:password]))
      session[:user] = user.id 
      redirect_to home_pages_path
    else
      flash[:message] = "Username Or Password Incorrect!!"
      redirect_to new_session_path
    end
  end

  def logout
    session[:user] = nil 
    redirect_to new_session_path
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<div class="booking-full-container">
    <div class="booking-heading">
        <h1>Edit Booking</h1>
        <p>We value your satisfaction</p>
    </div>
    <div class="error-text">
        <% if @booking.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@booking.errors.count, "error") %>
      prohibited this booking from being created:
    </h2>
 
    <ul>
    <% @booking.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
    </ul>
  </div>
  <br>
<% end %>
</div>

    <%= form_for @booking do |f|%>
        <%= f.hidden_field :guest_id, :value => @guest_id%>
        <%= f.hidden_field :room_id, :value => @room_id%>
        <%= f.label "Number of Guests", class: "label"%>
        <%= f.number_field :number_of_guest , class: "booking-field"%><br>
        <%= f.label "check In Date", class: "label"%>
        <%= f.date_field :check_in_date,:value => Date.parse(@booking.check_in_date), class: "booking-field"%> <br>
        <%= f.label "check Out Date", class: "label"%>
        <%= f.date_field :check_out_date, :value => Date.parse(@booking.check_out_date), class: "booking-field"%> <br>
        <%= f.hidden_field :booking_date, :value => Date.today%>
        <%= f.hidden_field :cost, :value => 0%>
        <%= f.submit "Submit Change"%>
    <%end%>
</div>

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

app/views/bookings/new.html.erb
<div class="booking-full-container">
    <div class="booking-main-container">
    <div class="booking-heading" >
        <h1>Create New Booking</h1>
    </div>

    <div class="menu-container">
            <div class="top-menu">
                <% if session[:user]%>
                    <button class="positive ui button">
                        <%= link_to "ACCOUNT", guest_path(Guest.find(session[:user])), method: :get%>
                    </button>
                    <button class="negative ui button">
                        <%= link_to "LOGOUT", logout_session_path, method: :get%>
                    </button>
                <%end%>
            </div>
        </div> 
<div class="error-text">
        <% if @booking.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@booking.errors.count, "error") %>
      prohibited this booking from being created:
    </h2>
 
    <ul>
    <% @booking.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
    </ul>
  </div>
  <br>
<% end %>
</div>

    <%= form_for @booking do |f|%>
        <%= f.hidden_field :guest_id, :value => @guest_id%>
        <%= f.hidden_field :room_id, :value => @room_id%>
        <%= f.label "Number of Guests", class: "label"%>
        <%= f.number_field :number_of_guest, placeholder: "Number of guest", class: "booking-field"%>  <br>
        <%= f.label "check In Date", class: "label"%>
        <%= f.date_field :check_in_date, class: "booking-field"%> <br>
        <%= f.label "check Out Date", class: "label"%>
        <%= f.date_field :check_out_date, class: "booking-field"%> <br>
        <%= f.hidden_field :booking_date, :value => Date.today%>
        <%= f.hidden_field :cost, :value => 0%>
        <button class="ui primary button">
            <%= f.submit "BOOK", class: "submit-booking"%>
        </button>
        <button class="ui red basic button">
            <%=link_to "CANCEL", home_pages_path %>
        </button>
        <%end%>
    </div>
</div>

app/views/bookings/show.html.erb
<div class="booking-full-container">
        <div class="booking-heading" >
                <h1>Booking Information</h1>
        </div>

        <div class="menu-container">
                <div class="top-menu">
                        <% if session[:user]%>
                        <button class="positive ui button">
                                <%= link_to "ACCOUNT", guest_path(Guest.find(session[:user])), method: :get%>
                        </button>
                        <button class="negative ui button">
                                <%= link_to "LOGOUT", logout_session_path, method: :get%>
                        </button>
                        <%end%>
                </div>
        </div>
        <div class="booking-congrate">
                <h3>Booking Success!!</h3>
        </div>
        <div class="booking-info">
                <h1>CheckIn Date: <%=@booking.check_in_date%></h1>
                <h1>CheckOut Date: <%=@booking.check_out_date%></h1>
                <h1>Number of Guest: <%=@booking.number_of_guest%></h1>
                <h1>Cost: $<%=@booking.cost%></h1>
                <h1>Guest First Name: <%=@booking.guest.first_name%></h1>
                <h1>Room Type: <%=@booking.room.room_type%></h1>
        </div>
        <div class="booking-buttons">
                <div class="edit">
                        <%= button_to "EDIT BOOKING", edit_booking_path(@booking), method: :get, class: "edit-booking"%>
                </div>
                <div class="delete">
                         <%= button_to "DELETE BOOKING", booking_path(@booking), method: :delete, class: "delete-booking"%>
                </div>
                    </div>

</div>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/guests/create.html.erb
<h1>Guests#create</h1>
<p>Find me in app/views/guests/create.html.erb</p>

app/views/guests/destroy.html.erb
<h1>Guests#destroy</h1>
<p>Find me in app/views/guests/destroy.html.erb</p>

app/views/guests/edit.html.erb
<h1>Guests#edit</h1>
<p>Find me in app/views/guests/edit.html.erb</p>

app/views/guests/index.html.erb
<h1>Guests#index</h1>
<p>Find me in app/views/guests/index.html.erb</p>
<hr>
<ol>
    <% @guests.each do |guest|%>
        <li>Name: <%=guest.first_name%> <%=guest.last_name%></li>
    <%end%>
</ol>

app/views/guests/new.html.erb
    <div class="signUpHeading">
            <h1>Sign up</h1>
            <p>Sign up for enjoy the best discount hotels</p>
    </div>

        <div class="sign-up-box">
                <div class="formSignUp">
                        <div></div>
                            <%= form_for @guest do |f| %>
                            <div class="row">
                                <%= f.label "First Name:", class: "label"%>
                                <%= f.text_field :first_name, placeholder: "first name", class: "guest-field"%> 
                            </div>
                            <div class="row">
                                <%= f.label "Last Name:", class: "label"%>
                                <%= f.text_field :last_name, placeholder: "last name", class: "guest-field"%>
                            </div>
                            <div class="row">
                                <%= f.label :email, class: "label"%>
                                <%= f.text_field :email, placeholder: "example@email.com",class: "guest-field"%>
                            </div>
                            <div class="row">
                            <%= f.label :password, class: "label"%>
                                <%= f.password_field :password, placeholder: "minimun 6 char", class: "guest-field"%> 
                            </div>
                            <div class="submit">
                                <%= f.submit "Create Guest", class: "guest-submit"%>
                                <%= link_to "Back", new_session_path, class: "guest-signIn" %>
                            </div>
                        <%end%>
                        <div></div>
                    </div>
                    
                    
        </div>

app/views/guests/show.html.erb
<div class="account-full-container">
  <div class="account-page-heading" >
    <h1>Account Information</h1> 
  </div>
    <div class="account-subMenu">
      <div class="top menu" style="text-align:right; margin:5px 0px">
          <% if session[:user]%>
          <button class="ui black basic button" disabled>
              <%=Guest.find(session[:user]).first_name.upcase%>
          </button>
          <button class="ui inverted red button">
                  <%= link_to "LOGOUT", logout_session_path, method: :get%>
          </button>
          <%end%>
      </div>
      <div class="search button" style="text-align:left">
          <button class="ui inverted primary button" >
              <span><i class="search icon"></i></span><%= link_to "Search Hotel", home_pages_path, method: :get%>
          </button>
          <button class="ui inverted primary button" >
              <span><i class="list icon"></i></span><%= link_to "Existing Reviews", reviews_path, method: :get%>
              </button>
      </div>
    </div>
  <br>

  <div class="ui one column"  style="margin:0px 200px">
          <div class="column">
            <div class="ui raised segment">
              <a class="ui blue ribbon label">Account Details</a>
              <h3><%= @guest.first_name%> <%= @guest.last_name%></h3>
              <h3>Email: <%= @guest.email%></h3>
            </div>
          </div>
        </div>
        <br>
<div class="account-cards-holder">
    <div class="ui cards">
      <% @bookings.each do |booking|%>
      <hr>
          <div class="card">
            <div class="content">
            <a href=<%=booking.room.hotel.image%> target="_blank"> <img class="right floated mini ui image" src=<%=booking.room.hotel.image%>  ></a>
              <div class="header">
                  Hotel Name: <%= link_to booking.room.hotel.name, hotel_path(booking.room.hotel)%>
              </div>
              <div class="description">
                  Checkin Date: <%=booking.check_in_date%>
              </div>
              <div class="description">
                  Checkout Date: <%=booking.check_out_date%> 
              </div>
              <div class="description">
                      Charged: $<%=booking.cost%>
              </div>
            </div>

            <div class="extra content">
              <div class="ui two buttons">
                <div class="ui basic green button">
                    <span><i class="edit outline icon"></i></span>  <%= link_to "EDIT", edit_booking_path(booking), method: :get%>
                </div>
                <div class="ui basic red button">
                     <span><i class="trash icon"></i></span> <%= link_to "DELETE", booking_path(booking), method: :delete%>
                </div>
              </div>
              <div class="ui basic button">
                      <%=form_tag new_review_path, method: :get do%>
                          <%=hidden_field_tag :hotel_id, booking.room.hotel.id%>
                         <span><i class="paper plane outline icon"></i></span> <%= submit_tag "WRITE A NEW REVIEW"%>
                      <%end%>
                </div>
            </div>
          </div>
      <%end%> 
  </div>
  </div>
</div>

app/views/guests/update.html.erb
<h1>Guests#update</h1>
<p>Find me in app/views/guests/update.html.erb</p>

app/views/home_pages/index.html.erb
<div class="background-full-container">
        
        <div class="home-header-container">
                <div class="page-heading">
                        <h1>Welcome To Hotel Booking</h1>
                </div>
            <div class="inner-home-header">
                <div class="menu-container">
                   <div class="top-menu">
                       <% if session[:user]%>
                           <button class="positive ui button">
                               <%= link_to "ACCOUNT", guest_path(Guest.find(session[:user])), method: :get%>
                           </button>
                           <button class="negative ui button">
                               <%= link_to "LOGOUT", logout_session_path, method: :get%>
                           </button>
                       <%end%>
                   </div>
                </div>  
                      
                   <div class="search" >
                   <%= form_with url: home_pages_path, method: :get, local: true do |f|%>
                   <%= f.select :city, @uniq_cities,{}, {:class=> "search_hotel"}%>
                       <div class="ui blue submit button">
                               <%= f.submit "SEARCH"%> <span><i class="search icon"></i></span>
                       </div>
                   <%end%>
                   </div>
            
                </div>
           </div>
<div class="home-full-container">
        <%if params[:city]%>
                   <h1>Hotels in <%=params[:city]%></h1>
               <%else%>
                   <h1>All Hotels</h1>
               <%end%>
        <div class="hotel-list-container">
            <div class="ui link cards">
                <% @hotels.each do |hotel|%>
                <%rooms = hotel.rooms.order(rate: :ASC)%>
                <% uniq_room = rooms.first(2)%>
                    <% uniq_room.each do |room|%>     
            
                    <div class="card" >
                        <div class="custom-image">
                            <img src=<%=room.image%> alt="">
                        </div>
                      <div class="content">
                        <div class="header">
                                Hotel Name: <%=link_to room.hotel.name, hotel_path(room.hotel)%>
                        </div>
                        <div class="header">
                                Room Type: <%=link_to room.room_type, room_path(room.id)%>
                            </div>
                        <div class="meta">
                          <%= room.hotel.city%>
                        </div>
                        <div class="room-rate">
                            <div class="room-description">
                                    $<%= room.rate%> / day
                            </div>
                        </div>
                      </div>
                      <div class="home-book-button">
                                  <%=link_to "Book", room_path(room.id)%>
                      </div>
                    </div>
                  
            <%end%>
            <%end%>
        </div>
    </div>
        
</div>

</div>
<div class="home-footer">
        <ul>
            <li>About website</li>
            <li>History</li>
            <li>Contact</li>
        </ul>
        <p>Copy right c Neeraj & Karma</p>
    </div>
    
          

app/views/hotels/index.html.erb
<h1>Hotels#index</h1>
<p><%@hotels.each do |h|%></p>
    <ul>
        <%=link_to h.name, hotel_path(h.id)%>
    </ul>
<%end%>

app/views/hotels/show.html.erb
<div class="full-container">
    <h1>Hotel Information</h1>
    <img src=<%=@hotel.image%>>
    <h2>Name: <%=@hotel.name%></h2>
    <h2>City: <%=@hotel.city%></h2>
    <h2>Country: <%=@hotel.country%></h2>
    <h2>
        Stars: <%if @hotel.reviews.average(:star)%>
                    <%while @i <= @hotel.reviews.average(:star)%>
                    <i class="star icon"></i>
                        <%@i += 1%>
                    <%end%>
                <%else%>
                    <%"There have been no reviews written for this hotel"%>
                <%end%>
    </h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelBooking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">  
  </head>

  <body style="text-align: center">
   
      <%= yield %>
   
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <script src="semantic/dist/semantic.min.js"></script>  
  </body>
</html>

app/views/reviews/index.html.erb
<div class="full-container">
  <div class="heading_page" style="background-color: rgb(24, 24, 233);color:white;padding:10px 0px">
      <h1>Reviews</h1></div>
  <br>
  <div class="menu-container">
      <div class="top-menu">
          <% if session[:user]%>
              <button class="positive ui button">
                  <%= link_to "ACCOUNT", guest_path(Guest.find(session[:user])), method: :get%>
              </button>
              <button class="negative ui button">
                  <%= link_to "LOGOUT", logout_session_path, method: :get%>
              </button>
          <%end%>
      </div>
  </div>  
  <br>

  <div class="ui cards">
  <%@guest.reviews.each do |review|%>
  <div class="ui card">
          <div class="content">
            <div class="card-image">
              <img src=<%=review.hotel.image%> alt="">
            </div>
            <div class="header"><%=review.title%></div>
            <div class="meta"><%=review.hotel.name%>, <%=review.hotel.city%></div>
            <div class="meta"><%=review.created_at.strftime("%B %d %Y")%></div>
            <div class="meta">
              <%review.star.times do%>
                <span><i class="star icon"></i></span>
              <%end%>
            </div>
            <div class="description">
              <p style="overflow: auto">
                <%=review.content%>
              </p>
            </div>
          </div>
        </div>
  <%end%>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="review-full-container">
    <div class="heading-page" style="background-color: rgb(24, 24, 233);color:white;padding:10px 0px">
            <h1>New Review</h1>
    </div>

    <div class="menu-container">
            <div class="top-menu">
                <% if session[:user]%>
                    <button class="positive ui button">
                        <%= link_to "ACCOUNT", guest_path(Guest.find(session[:user])), method: :get%>
                    </button>
                    <button class="negative ui button">
                        <%= link_to "LOGOUT", logout_session_path, method: :get%>
                    </button>
                <%end%>
            </div>
    </div>  
        <div class="review-header">
            <h3><%=@hotel.name%></h3>
        </div>
<div class="review-error">
    <% if @review.errors.any? %>
    <div id="error_explanation">
        <h2>
        <%= pluralize(@review.errors.count, "error") %>
        prohibited this review from being posted:
        </h2>
    
        <ul>
        <% @review.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
        <% end %>
        </ul>
    </div>
    <br>
    <% end %>
</div>


    <%=form_for @review do |review|%>
    <div class="review-form">
        <div>
        <%=review.label "Title", class: "review-label"%> 
        </div>
        <div>
        <%=review.text_field :title, placeholder: "Title", class: "review-field"%> 
        </div>
        <div>
        <%=review.label "Star", class: "review-label"%>
        </div>
        <div>
        <%=review.select :star, [1,2,3,4,5],{},class: "review-select"%> 
        </div>
        
        <div>
        <%=review.label "Content", class: "review-label"%>
        </div>
        <div>
        <%=review.text_area :content, placeholder: "Content", class: "review-field"%> <br>
        </div>
        <%=review.hidden_field :hotel_id, :value=> @hotel.id%>
    </div>
        <div class="review-post-button">
           <span><i class="paper plane outline icon"></i></span><%=review.submit "Post-Review", class: "review-post"%> 
        </div>
        
    
  <%end%>

</div>

app/views/rooms/index.html.erb
<div class="full-container">
    <h1>Rooms#index</h1>
    <p>Find me in app/views/rooms/index.html.erb</p>
    <hr>
    <ol>
        <% @rooms.each do |room|%>
            <li>Room Type: <%= room.room_type%></li>
            <li>Room Rate: <%= room.rate%></li>
        <%end%>
    </ol>
    <hr>
</div>

app/views/rooms/show.html.erb
<div class="room-full-container">
    <div class="room-main-container">
    <div class="room-page-heading">
        <h1><%=@room.room_type%> Room</h1>
    </div>
    <div class="menu-container">
        <div class="top-menu">
            <% if session[:user]%>
                <button class="positive ui button">
                    <%= link_to "ACCOUNT", guest_path(Guest.find(session[:user])), method: :get%>
                </button>
                <button class="negative ui button">
                    <%= link_to "LOGOUT", logout_session_path, method: :get%>
                </button>
            <%end%>
        </div>
    </div> 
    <div class="room-details">
        <div class="room-img">
            <img src=<%=@room.image%> alt="room image">
        </div>
        <div class="room-type">
            Room type: <%=@room.room_type%>
        </div>
        <div class="room-show-rate">
            Cost per day: $<%=@room.rate%>
        </div>
        
        <%= form_tag new_booking_path, method: :get do %>
            <%= hidden_field_tag :room_id, @room.id%>
            <%= submit_tag "BOOK THIS ROOM", class: "room-book-submit"%>
        <%end%>
    </div>
</div>
</div>

    